# Generated by Django 3.1.3 on 2020-11-30 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('VENDOR', 'Vendor'), ('BIDDER', 'Bidder')], max_length=10)),
                ('company_name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=15)),
                ('telephone', models.CharField(max_length=15)),
                ('address_line_one', models.CharField(max_length=25)),
                ('address_line_two', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('postal_zip', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
